//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShark.PCShark.DAL.SQLiteLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardVariation
    {
        public long Id { get; set; }
        public long CardId { get; set; }
        public string SetCode { get; set; }
        public string FlavorText { get; set; }
        public string Author { get; set; }
        public string Artist { get; set; }
        //public byte[] FullCardImage { get; set; }
        public int NumberOwned { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Set Set { get; set; }
    }
}
