//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShark.PCShark.DAL.SQLiteLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.CardVariations = new HashSet<CardVariation>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        //public string ManaCost { get; set; }
        //public string CardType { get; set; }
        public string RuleText { get; set; }
        public Nullable<int> PowerVal { get; set; }
        public string PowerVar { get; set; }
        public Nullable<int> ToughnessVal { get; set; }
        public string ToughnessVar { get; set; }
        public Nullable<int> LoyaltyVal { get; set; }
        public string LoyaltyVar { get; set; }
        public string Author { get; set; }
    
        public virtual ICollection<CardVariation> CardVariations { get; set; }
    }
}
