//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShark.PCShark.DAL.SQLiteLocal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalCardDataEntities : DbContext
    {
        public LocalCardDataEntities()
            : base("name=LocalCardDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Card> Cards { get; set; }
        public DbSet<CardVariation> CardVariations { get; set; }
        public DbSet<ManaSymbol> ManaSymbols { get; set; }
        public DbSet<ManaSymbolSet> ManaSymbolSets { get; set; }
        public DbSet<Set> Sets { get; set; }
    }
}
