//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShark.PCShark.DAL.SQLiteLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManaSymbol
    {
        public string Code { get; set; }
        public Nullable<long> ManaSymbolSetId { get; set; }
        //public byte[] Image { get; set; }
    
        public virtual ManaSymbolSet ManaSymbolSet { get; set; }
    }
}
