//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShark.PCShark.DAL.SQLiteLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        public Set()
        {
            this.CardVariations = new HashSet<CardVariation>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        //public byte[] CommonSymbol { get; set; }
        //public byte[] UncommonSymbol { get; set; }
        //public byte[] RareSymbol { get; set; }
        //public byte[] MythicSymbol { get; set; }
        //public byte[] SpecialSymbol { get; set; }
        public bool IsOfficial { get; set; }
        public Nullable<long> ManaSymbolSetId { get; set; }
    
        public virtual ICollection<CardVariation> CardVariations { get; set; }
        public virtual ManaSymbolSet ManaSymbolSet { get; set; }
    }
}
